export const projectData = [
  {
    theme: "normal",
    projectName: "GuiTab吉他譜生成網站",
    projectIntro: "一鍵獲取完整吉他譜，使喜歡的音樂永遠保存",
    projectDescription:
      "GuiTab 是一個能夠根據使用者提供的 YouTube 影片網址（需包含 Tab 譜）自動生成完整吉他譜的網站。使用者只需輸入 YouTube 影片的網址，系統將擷取影片畫面，使用者可以選擇 TAB 區域，最後系統將生成完整的吉他譜。",
    backgroundVideoName: "guitar_3",
    url: "https://github.com/a880630a/GuiTab",
    imgName: "GuiTab.png",
    projectSkill: [
      "React",
      "JavaScript",
      "SCSS",
      "Python",
      "Flask",
      "Git",
      "Docker",
      "Linux",
    ],
  },
  {
    theme: "normal",
    projectName: "AS/RS自動倉儲模擬系統",
    projectIntro: "透過模擬，了解實際狀況",
    projectDescription:
      "使用者可以透過該系統或取到各個倉儲資訊以及即時的車體位置與地圖資訊，可快速了解整體倉儲系統的運作狀況(此系統為協同開發，主要負責項目為畫面上地圖及車體更新、地圖上即時車輛行走路徑)",
    backgroundVideoName: "ASRS",
    url: "https://github.com/a880630a/GuiTab",
    imgName: "asrs_s.jpg",
    projectSkill: [
      "React",
      "JavaScript",
      "SCSS",
      "Next.JS",
      "TailwindCSS",
      "Python",
      "Flask",
      "Ros",
      "Git",
      "Docker",
      "Linux",
    ],
  },
  {
    theme: "normal",
    projectName: "AGV派車系統",
    projectIntro: "UI派車，方便操作",
    projectDescription:
      "使用者可進行AGV多條件功能派車選擇與即時更新的AGV派車地圖，並與後端溝通可快速的確認目前的AGV位置與車輛狀態資訊，並結合動畫使網頁互動性增加。",
    backgroundVideoName: "AGV",
    url: "https://github.com/a880630a/GuiTab",
    imgName: "派車系統_s.png",
    projectSkill: [
      "React",
      "JavaScript",
      "SCSS",
      "Python",
      "Flask",
      "Ros",
      "Git",
      "Linux",
    ],
  },
  {
    theme: "dark",
    projectName: "燃料稅與牌照稅計算網站",
    projectIntro: "條件選擇，解決你算數學的煩惱",
    projectDescription:
      "使用者可進行AGV多條件功能派車選擇與即時更新的AGV派車地圖，並與後端溝通可快速的確認目前的AGV位置與車輛狀態資訊，並結合動畫使網頁互動性增加。",
    backgroundVideoName: "tax",
    url: "https://github.com/a880630a/GuiTab",
    imgName: "牌照稅.png",
    projectSkill: ["React", "JavaScript", "SCSS", "Linux"],
  },
];
